### ISSUE TITLE
非单例service生命周期

### ISSUE THREAD

**Issue by winterbesos** [alibaba/BeeHive#10]
service创建的时候会加入到servicesByName的dictionary中，但是service不再使用的时候并不能及时的dealloc，而是在下一个同样的service创建的时候进行的dealloc，这样会增加一些service本身的资源开销。

能否增加协议在模块出口处释放资源？

**Comment by 778477** [comment]
恩，是的。这个很有必要，BeeHive会把注册服务变成"单例"。延长了生命周期

**Comment by rexqin** [comment]
这是一个设计模式的问题  如果允许注销service的话 容易导致其它模块里API调用不可用。同时注销的行为对于其它模块也是不可见的。我能想到的一种解决方法是，当发现API不可用的时候，去查询API归属的service，然后重新自动注册servcie  类似比较常见的多进程模块唤起机制。不知道有没有更好的解题思路

**Comment by wanyakun** [comment]
@rexqin service 在使用之前是通过- (id)createService:(Protocol *)service来获得实例的，每次都会重新生成（单例除外），普通service 实例生成后会被保存到BHContext的servicesByName字典中，而不能够被释放的问题，除非再次生成实例重新保存时才能释放旧的实例。而保存起来的实例，好像并没有什么用处。
通过Protocol 生成的service，应该在超出自己的作用域之后自动释放才对吧？

**Comment by yaochenfeng** [comment]
这个现在已经不存在了吧
