### ISSUE TITLE
推送收不到的奇怪问题

### ISSUE THREAD

**Issue by passol1988** [alibaba/BeeHive#124]
当我在自己AppDelegate（当然继承BHAppDelegate）里加上
```
[super application:application didFinishLaunchingWithOptions:launchOptions];
```
怎么都收不到推送，不加就能收到。不太懂其中的原理

**Comment by SoXeon** [comment]
你可以debug试一下

**Comment by conanwsz** [comment]
跟推送相关的的确是不会走到BHAppDelegate里去。可以在AppDelegate中实现推送相关的delegate，然后手动调super方法。

**Comment by passol1988** [comment]
@conanwsz 谢谢，在实际使用中也找到了。设置了`UNUserNotificationCenter`的代理通知会被接管。
