### ISSUE TITLE
提个建议： 英文文档图中不要夹杂着中文

### ISSUE THREAD

**Issue by zhaoxiaobao** [alibaba/BeeHive#14]
![](https://camo.githubusercontent.com/5701febbbbfd56c5e6103ca8696b8f67e6a406c5/687474703a2f2f67746d7330312e616c6963646e2e636f6d2f7470732f69312f5442314f727358494658585858616f584658586a574331387058582d313131392d3535322e6a7067)

英文文档图中夹杂着中文，显得有点不走心~~~

😝

**Comment by oldratlee** [comment]
@zhaoxiaobao 方便的话，直接更新一下图/文档文件，提供图的源文件，并给个PullRequest。

PS： 可以把文档相关的内容放到子目录`docs`中。

期待你的贡献 :)

**Comment by oldratlee** [comment]
PR #15 已经合并。 多谢 @zhaoxiaobao 的贡献！
