### ISSUE TITLE
context的env是只读的，我哪里去改变env？

### ISSUE THREAD

**Issue by captain-black** [alibaba/BeeHive#16]
context的env是只读的，我哪里去改变env？

**Comment by kd0025** [comment]
@property(nonatomic, assign) BHEnvironmentType env;
这里的env是可写的，可以去更改env

**Comment by captain-black** [comment]
额，我发现pod出来的1.0.0是readonly...好吧，我自己改一下这属性好了。谢谢。 @kd0025

**Comment by rexqin** [comment]
@captain-black  属性初始化的时候可以设置env的值，readonly是防止中间有人再次修改
