### ISSUE TITLE
单词拼写错误

### ISSUE THREAD

**Issue by sunbohong** [alibaba/BeeHive#18]
https://github.com/alibaba/BeeHive/blob/master/Docs/system-event-workflow-en.png
lunch->launch

**Comment by oldratlee** [comment]
@sunbohong 欢迎给一个 Pull Request，这样别人也可以直接在工程里看到你的贡献～

**Comment by sunbohong** [comment]
@oldratlee  你好，请问这些图片是用什么工具生成？我尽量和文中图片的样式保持一致

**Comment by oldratlee** [comment]
@sunbohong 👍 

源文件应该找不到了，你可以用 像 `Graffle`/`PowerPoint`/`KeyNote` 画图：

- 导出图片替换
- 把图的源文件也在PR中提交上来

**Comment by oldratlee** [comment]
Fixed.
