### ISSUE TITLE
“系统事件基本工作流”的图片中对“进入前台”的描述有误

### ISSUE THREAD

**Issue by sunbohong** [alibaba/BeeHive#19]
https://camo.githubusercontent.com/5701febbbbfd56c5e6103ca8696b8f67e6a406c5/687474703a2f2f67746d7330312e616c6963646e2e636f6d2f7470732f69312f5442314f727358494658585858616f584658586a574331387058582d313131392d3535322e6a7067

图片中是 “WillEnterBackground”，正确地描述应该是 "WillEnterForeground"

**Comment by SoXeon** [comment]
已修改，谢谢提醒。
