### ISSUE TITLE
下载下来Example编译不通过

### ISSUE THREAD

**Issue by AaronZhang2015** [alibaba/BeeHive#2]
```bash
ld: library not found for -lBeeHive
```

**Comment by SoXeon** [comment]
使用的cocoapod是什么版本？

**Comment by maxwell44** [comment]
我的是1.0.1 也编译不过

**Comment by SoXeon** [comment]
适配好了，再试试看

**Comment by SoXeon** [comment]
适配好了，再试试看

**Comment by AaronZhang2015** [comment]
并没有解决

**Comment by maxwell44** [comment]
ld: library not found for -lBeeHive

**Comment by kd0025** [comment]
cocoapods目前发布的最新版本是1.0.0吧

**Comment by kd0025** [comment]
我这边1.0.1可以编译，看看你的pod版本是不是beta

**Comment by helinyu** [comment]
怎么用pod拉取不到？
[!] Unable to find a specification for `BeeHive (= 1.0.0)`

![image](https://cloud.githubusercontent.com/assets/6794638/17928459/56546b42-6a2d-11e6-8026-5ab0b7d8cb6f.png)

**Comment by SoXeon** [comment]
我这边看过cocoapods的specGit记录，的确是有的，请确保repo是最新的

**Comment by maxwell44** [comment]
ld: library not found for -lBeeHive
clang: error: linker command failed with exit code 1 (use -v to see invocation)

下载后 依然编译不了

**Comment by kd0025** [comment]
@maxwell44 看看这个能不能帮到你 https://segmentfault.com/q/1010000003780100   应该是你的pod问题

**Comment by maxwell44** [comment]
@kd0025  我移除了我POD 重新安装了一次. 还是无济于事...

**Comment by Resory** [comment]
我试了下，需要pod install 两次就ok了。第一次提示

**Comment by Huang-Libo** [comment]
pod v1.1.1 可以顺利安装

**Comment by hebiao6446** [comment]
自己新建一个工程，将相关的东西拉进去，就可以启动 ，
但是不太明白这个设计模式有哪些优势。。。

**Comment by SoXeon** [comment]
@hebiao6446 优势在解决大型iOS工程中协作开发，降级依赖关系，减少block问题，规模较小的工程不建议使用。
