### ISSUE TITLE
BeeHive有哪些优势了 ？

### ISSUE THREAD

**Issue by hebiao6446** [alibaba/BeeHive#27]
项目下载下来看了下，网上的确找不到什么资料来解释这种模式的作用，我感觉就是简单的问题复杂化了，这种模式的优势在哪里了 ？  明明一个类可以解决的问题，为啥还要分为一个类和一个代理了 ？？？？？？？？

**Comment by SoXeon** [comment]
先看业务场景以及团队规模，在天猫客户端中涉及人员较多，业务也复杂，N个团队之间不同模块的解耦就是优势。

**Comment by rexqin** [comment]
Beehive并不是一种设计模式，是一个ios下插件化的应用框架，在大规模的人员开发时，可以将多模块的开发标准化成对插件生命周期以及调用API的管理，避免过于复杂的依赖关系

**Comment by oldratlee** [comment]
@SoXeon 推荐在README中加上适用场景的说明～
