### ISSUE TITLE
English Documentation need more review

### ISSUE THREAD

**Issue by JasonWorking** [alibaba/BeeHive#37]
英文版的Doc建议找专人Review一下. 
如Weichat,应该是 Wechat.  一些语序也可以调整下.

**Comment by oldratlee** [comment]
开源项目 @JasonWorking 一起来做吧～

欢迎 [Fork](https://github.com/alibaba/BeeHive#fork-destination-box) 后 发PR，合并你的提交 好出现在 主提交树里的~ 😄
