### ISSUE TITLE
Service 跟 Module 有什么区别

### ISSUE THREAD

**Issue by arkilis** [alibaba/BeeHive#38]
```
[BHContext shareInstance].moduleConfigName = @"BeeHive.bundle/BeeHive";//可选，默认为BeeHive.bundle/BeeHive.plist
[BHContext shareInstance].serviceConfigName = @"BeeHive.bundle/BHService";
```

代码中看到的，请问Service 跟 Module 有什么区别呢？谢谢

**Comment by SoXeon** [comment]
Module相当于一个功能级别的聚合，它能感知App的统一上下文，以及生命周期，避免在AppDelegate中出现耦合，可以把单一功能抽到一个Module中。
Service相当于某个具体功能，这种功能可以是某个Module提供出来的，也可以是别的形式，这是为了便于统一模块间的服务调度，只暴露接口，这样模块间可以更加内聚。

**Comment by arkilis** [comment]
多谢
