### ISSUE TITLE
单词拼写有误

### ISSUE THREAD

**Issue by panshimin1112** [alibaba/BeeHive#40]
在 BHAppDelegate 文件中
![image](https://cloud.githubusercontent.com/assets/7685633/21633493/a64eb7b8-d28a-11e6-8298-2520258e2f14.png)

**Comment by oldratlee** [comment]
@panshimin1112 你改一下，给个Pull Request。

你看一下是不是 API相关，如果不是这样的拼写修改是没有风险的。

**Comment by oldratlee** [comment]
@panshimin1112 已经修复了～
