### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by sun6boys** [alibaba/BeeHive#44]
你好，今天深入解读该框架源码，发现了一些框架中问题，我已经把问题列在我的一篇博客中 http://www.jianshu.com/p/76e2377a6fb4  希望能尽快更正，毕竟会有一些外国友人用到它。

**Comment by SoXeon** [comment]
1. 两处错别字，下个版本改正。
2. BHConfig是为后续扩展占坑，主要用于在于全局需要用到一些配置项，空格问题review不够，下个版本改正
3. BHEnvironmentType 是指大环境，比如线上，预发，日常，不需要有太多扩展，各自业务的Type，自己内部定义就好。
4. 感谢指出BeeHive的相关问题，欢迎提Pull Request
