### ISSUE TITLE
v1.2.0 关于BHContext的疑问

### ISSUE THREAD

**Issue by raomengyun** [alibaba/BeeHive#52]
先前通过继承`BHContext`来定义了一个`CustomContext`来存放**公共环境变量**，例如服务器环境，服务器基址等信息。

### 问题
`v1.2.0`版本代码有些改动，`BHModuleManager`类以及`BHServiceManager`类内部对于`plist静态模块加载`、`plist静态服务加载`、`模块生命周期事件触发`均是引用`[BHContext shareInstance]`对象，然而`BHAppDelegate`中对于`touchShortcutItem`、`openURLItem`、`notificationsItem`、`userActivityItem`等属性的赋值却是针对于 **[BeeHive shareInstance].context**的。

### 结论
结论就是说我们在使用`plist`进行模块或者服务的静态注册是我们需要使用[BeeHive shareInstance]来配置plist的路径，而对于`touchShortcutItem`、`openURLItem`、`notificationsItem`、`userActivityItem`等属性的取值我们要使用`CustomContext`。这是否与BeeHive的设计初衷不一致？

**Comment by SoXeon** [comment]
其实context用到的是同一个BHContext的单例，这里表述没有清楚，后面会逐步改掉的。

**Comment by raomengyun** [comment]
恩，期待后续更新👍
