### ISSUE TITLE
每一个ViewController通过createService去初始化和原来有什么区别？优势在哪里？

### ISSUE THREAD

**Issue by yuqian666** [alibaba/BeeHive#54]
ServiceProtocol里面的方法和原来h文件暴露的方法不是一样的作用吗？感觉就是ViewController中暴露的方法位置移了一下，然后ViewController的初始化方法变了。。。感觉没有领悟到精髓啊！求解答！！！

**Comment by SoXeon** [comment]
在一个简单工程中，可能某个Service不需要以Protocol形式去提供出去，业务方直接拿来引入用即可，但一旦调用者居多，或者你提供的Service中包含了其他Service，比如你提供一上层的业务Service用到了配置Service，用到了日志Service，用到了登陆Service，这样的依赖关系是非常可怕的。

那么我们需要的是拆散模块之间的直接依赖，以AOP形式，提取某个Service的Interface，开发方和调用方以此作为约定，横向的提供给不同的调用者，这样一方面收敛了代码，另一方面你不需要关心到底引入一个服务附带的要附带上其他东西，你关心你的业务流程即可。

**Comment by yuqian666** [comment]
如果只是要进行页面跳转而没有方法暴露出来，是不是就没必要创建Service？然后在ModuleProtocol里面除了一些init、modSetUp方法外我们该在里面做些什么其他的东西吗？

**Comment by SoXeon** [comment]
可以参考https://github.com/joeldev/JLRoutes，这相当于在BeeHive上层做了一层Router解决跳转问题的解决方案。

**Comment by yuqian666** [comment]
感觉demo里module都没有什么作用啊，例子内容太少了，完全看不出Module怎么跟service联系起来

**Comment by SoXeon** [comment]
Module 和 Service 本身没有关联，Module用来感知App生命周期，Service用来提供服务Interface

**Comment by yuqian666** [comment]
感知app生命周期在APPDelegate里不就可以了，有必要每个Module里都有吗？能不能举个例子说明一下

**Comment by raomengyun** [comment]
每个Module单独处理App生命周期时间，原理也是为了解耦，职责分离。

**Comment by ZoMinster** [comment]
每个module只对应一个viewcontroller吗

**Comment by kd0025** [comment]
每个module对应一个模块粒度

**Comment by ZoMinster** [comment]
也就是说可以对应多个viewcontroller是吗

**Comment by heeween** [comment]
其实就是原本控制器直接依赖改为依赖service了。把所有的依赖统一写到service。每个业务组件都要依赖service。各业务组件来共同维护service这个组件。感觉谈不上什么架构吧，算作代码整理吧。
