### ISSUE TITLE
目前哪些应用使用了该框架呢?

### ISSUE THREAD

**Issue by Erik5169** [alibaba/BeeHive#56]
您好, 想知道下, 目前这个框架, 有在哪些应用中使用, 稳定性怎么样? 还有个问题是, 如何按需依赖注入组件

**Comment by SoXeon** [comment]
1. 天猫，流量排名第四的电商App，使用一年多了，稳定性可靠，集团以外暂不清楚。
2. 按需依赖，通过plist、Annotation、dynamic三种形式注入组件，readme中有写到[link](https://github.com/alibaba/BeeHive/blob/master/README-CN.md#2-%E6%A8%A1%E5%9D%97%E6%B3%A8%E5%86%8C)
