### ISSUE TITLE
为什么BHService.plist放在pods里面，但是它的实现文件却放在项目里面

### ISSUE THREAD

**Issue by mario-huang** [alibaba/BeeHive#59]
它们不是应该一起放到pods里面吗。感觉demo还是太简单了，体现不出你们的目的。

**Comment by SoXeon** [comment]
1. 这是一开始设计时的一个缺陷，我们准备后续移除来，比如集中Service Interface的Pod中。
2. demo的确比较简单，写复杂了成本划不来，又不能直接复制业务代码，这个有风险。
