### ISSUE TITLE
在引入BeeHive的工程里，一些组件的配置应该放在那个地方呢？

### ISSUE THREAD

**Issue by waterfly** [alibaba/BeeHive#61]
比如我们目前的工程里，一些组件需要外部环境参数配置，目前是放在 didFinishLaunchingWithOptions 里，然后项目依赖这些组件。在引入BeeHive后，这些组件的合适位置应该是放在那里？是应该作为Module 一样，每个组件都创建一个Module 管理组件的生命周期，还是只建一个公共Module 统一管理这些组件？

另外，麻烦再问下，每个项目做成插件后，独立运行的基础是 项目代码依赖一个统一的工程配置吗？比如说各种组件的初始化配置，都放在一个工程壳子里，然后每个项目代码加上这个壳子就能独立编译运行

**Comment by SoXeon** [comment]
1. 建议一开始以功能维度独立抽离Module，别整个什么CommonModule，最后这个module会非常乱，非常难维护！

2. 这个初始化配置，建议建一个ServiceInterface的pod or submodule 将初始化配置Module和Service、Service Interface都放到里面，其他开发者只要关注这里的接口变化即可。
