### ISSUE TITLE
Service返回对象类型声明的建议

### ISSUE THREAD

**Issue by maxfong** [alibaba/BeeHive#64]
```objc
id<UserTrackServiceProtocol> v4 = [[BeeHive shareInstance] createService:@protocol(UserTrackServiceProtocol)];
if ([v4 isKindOfClass:[UIViewController class]]) {
    [self registerViewController:(UIViewController *)v4 title:@"埋点3" iconName:nil];
}
```   

`id`的具体类型需要项目间约定，能否在Protocol的声明文件中就标注返回类型是什么？
比如做约定：  

```objc
#import <Foundation/Foundation.h>
#import "BHServiceProtocol.h"

@class UIViewController;  //表示当前协议返回类型为UIViewController
@protocol UserTrackServiceProtocol <NSObject,BHServiceProtocol>

@end
```  

毕竟Protocol只能绑定一种类型。

**Comment by SoXeon** [comment]
1. 是一种不错的建议，这种场景下需要知道返回类型。
2. 但Protocol，Service Interface并不用太过关注协议实现的返回类型，而是关注具体的Service方法即可，这里的例子有所偏差。

**Comment by maxfong** [comment]
完全按Protocol实现如果绑定类型丰富的话需要添加很多方法，开放类型声明会更方便的使用。
当然这和BeeHive的设计冲突，但使用场景可能这样居多。

**Comment by maxfong** [comment]
完全按Protocol实现如果绑定类型丰富的话需要添加很多方法，开放类型声明会更方便的使用。
当然这和BeeHive的设计冲突，但使用场景可能这样居多。

**Comment by maxfong** [comment]
懂你的意思。
但完全按Protocol实现如果绑定类型丰富的话需要添加很多方法，开放类型声明会更方便的使用。
当然这和BeeHive的设计冲突，但使用场景可能这样居多。
