### ISSUE TITLE
关于 BHServiceProtocol 单例的疑问

### ISSUE THREAD

**Issue by laichanwai** [alibaba/BeeHive#71]
在 `BHServiceProtocol` 中定义了`shareInstance`这个方法，那么我通过 `createService:` 获取一个单例对象的时候，为什么单例对象不是通过我实现的方法创建？

```objc
Class implClass = [self serviceImplClass:service];
Method clzSingleMethod = class_getInstanceMethod(implClass, @selector(singleton));
Method insSingleMethod = class_getClassMethod(implClass, @selector(singleton));
if (clzSingleMethod == NULL &&
    insSingleMethod == NULL) {
    return [implClass new];
}

implInstance = [[implClass alloc] init];
NSString *serviceStr = NSStringFromProtocol(service);
[[BHContext shareInstance] addServiceWithImplInstance:implInstance serviceName:serviceStr];
return implInstance;
```

在上面 `BHServiceManager` 的 `createService:` 实现中，只是判断了是否实现了 `singleton` 方法，然后是通过 `[[implClass alloc] init]` 创建的单例。

**Comment by SoXeon** [comment]
这里是为了便于统一，自己实现的创建方法是有入参吗？

**Comment by waterfly** [comment]
有些类是需要自己创建的单例，感觉判断下是否实现 `+ (id)shareInstance `  会更好

**Comment by laichanwai** [comment]
@SoXeon 我的疑问是，你定义了创建单例的方法，我遵循了你的方法返回一个单例，可为什么你没有使用？

**Comment by SoXeon** [comment]
implInstance = [[implClass alloc] init];
这边的确不太合理，如果是一个单例Service的话直接调类方法就好，但方法名不一致的话，不好判断

**Comment by SoXeon** [comment]
已合并
