### ISSUE TITLE
BeeHive/BHWatchDog.m:95:5: warning: Returning 'self' while it is not set to the result of '[(super or self) init...]

### ISSUE THREAD

**Issue by shuixin536** [alibaba/BeeHive#75]
- (instancetype)initWIthThreshold:(double)threshold callBack:(watchdogFiredCallBack)callBack
{
    if ([self init]) {
        self.threshold = 0.4;//默认间隔
        self.threshold = threshold;
        self.pingThread = [[PingThread alloc] initWithThreshold:threshold handler:callBack];
        [self.pingThread start];
    }
   
    return self;
}

self没有赋值self = [self init]

**Comment by SoXeon** [comment]
fix it in lastest master
