### ISSUE TITLE
xcode8.3,cocopad 1.2.0.beta.1  .  集成版本pod "BeeHive", '1.5.0' 。  运行出错

### ISSUE THREAD

**Issue by wscqs** [alibaba/BeeHive#77]
控制台一直显示*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'MainControllerProtocol protocol does not been registed'

自己解决了：在BHAnnotation.h需增加
@interface BHAnnotation
@end

在BHAnnotation.m需增加
@implementation BHAnnotation
@end

希望 cocopod版本 及时更新解决

**Comment by SoXeon** [comment]
我看master上是有了
![image](https://cloud.githubusercontent.com/assets/7249401/26273918/2e77183a-3d6e-11e7-8269-504a425b408b.png)

**Comment by wscqs** [comment]
但是cocopod  1.5.0  集成进去没有。      这是重点，你可以集成试下。  我就是参考master才发现这个导致运行出错（用@声明注入方式）的根源。

**Comment by SoXeon** [comment]
谢谢指出问题，已更新最新pod 1.5.1并修复
