### ISSUE TITLE
我某个class即实现了自定义service的protocol，又要实现系统的protocol，这个时候单例就不起作用了

### ISSUE THREAD

**Issue by friendtimes** [alibaba/BeeHive#78]

**Comment by SoXeon** [comment]
有具体代码吗？

**Comment by Dcell** [comment]
- (id)createService:(Protocol *)service
{
    id implInstance = nil;
    
    if (![self checkValidService:service] && self.enableException) {
        @throw [NSException exceptionWithName:NSInternalInconsistencyException reason:[NSString stringWithFormat:@"%@ protocol does not been registed", NSStringFromProtocol(service)] userInfo:nil];
    }
    
    id protocolImpl = [[BHContext shareInstance] getServiceInstanceFromServiceName:NSStringFromProtocol(service)];
    if (protocolImpl) {
        return protocolImpl;
    }
    
    Class implClass = [self serviceImplClass:service];
    Method clzSingleMethod = class_getInstanceMethod(implClass, @selector(singleton));
    Method insSingleMethod = class_getClassMethod(implClass, @selector(singleton));
    if (clzSingleMethod == NULL &&
        insSingleMethod == NULL) {
        return [implClass new];
    }

    implInstance = [[implClass alloc] init];
    NSString *serviceStr = NSStringFromProtocol(service);
    [[BHContext shareInstance] addServiceWithImplInstance:implInstance serviceName:serviceStr];
    return implInstance;
}


没看懂，用户自定义的单例体现在哪？
1.5.0

**Comment by oldratlee** [comment]
Issue did not provide reproduce info, close first! 

@friendtimes Please provide reproduce info, then we will reopen this issue.
