### ISSUE TITLE
能否指点下BHAnnotation宏定义中关于双引号的使用

### ISSUE THREAD

**Issue by seuzxh** [alibaba/BeeHive#80]
您好，想请教一下，
在 `#define BeeHiveMod(name)` 中，有一个宏定义为：```
#define BeeHiveMod(name) \
char * k##name##_mod BeeHiveDATA(BeehiveMods) = ""#name"";```其中的`#name`两侧分别使用了两个双引号`”“`

如果业务使用 `#define BeeHiveMod(BeehiveMods)`
最终展开形式为：
`char * kShopModule_mod __attribute((used, section("__DATA,""BeehiveMods"" "))) = """ShopModule""";`

注册的 `ShopModule` 使用了六个引号。。。 `"""ShopModule"""`

这里为什么在设计时会采用这么多的双引号，我尝试使用一下两种也是正确的。。：

- 使用一个双引号 `"`

```
#define BeeHiveMod(name) \
char * k##name##_mod BeeHiveDATA(BeehiveMods) = "#name";
```

- 不使用双引号

```
#define BeeHiveMod(name) \
char * k##name##_mod BeeHiveDATA(BeehiveMods) = #name;
```

非常感谢您的回答

**Comment by SoXeon** [comment]
注解设计逻辑可参考这篇文章，http://www.jianshu.com/p/24f6299ebe82
