### ISSUE TITLE
细细的问一句，能否把GPL协议改成MIT协议

### ISSUE THREAD

**Issue by Dcell** [alibaba/BeeHive#92]
如题。
项目中想集成Beehive框架

**Comment by oldratlee** [comment]
GPLv2 是可以商业使用的。

![image](https://user-images.githubusercontent.com/1063891/29778114-d1869d2c-8c40-11e7-866e-aae6ee540313.png)

你有什么问题吗？

**Comment by Dcell** [comment]
如果BeeHive 用了GPL协议，是不是意味着 所有集成BeeHive源码的项目，都必须要开源？
不是很清楚移动应用是如何遵循GPL协议的，是不是只要对外发布，那么必须开源么？

**Comment by AcerFeng** [comment]
@Dcell 这协议是说你如果对这个项目做了修改必须开源，不是用了这个项目就要开源自己的源码

**Comment by oldratlee** [comment]
@AcerFeng 如所说。

各种具体协议的信息，自己要去了解好哦。 @Dcell

**Comment by met-pub** [comment]
只要在一个软件中使用(“使用”指类库引用或者修改后的代码) GPL 协议的产品，则该软件产品必须也采用GPL协议，既必须也是开源和免费。
