### ISSUE TITLE
这就是一个KPI项目

### ISSUE THREAD

**Issue by humt0ng** [alibaba/BeeHive#93]
编码规范差，注释严重缺失，接口设计混乱， 没有UT

居然能设计出BHContext这样的东西

**Comment by oldratlee** [comment]
@humt0ng 如果你觉得可以做的更好，可以多提PR，解决你说的这些问题。

1.  改进总得来说总是有余地。这等价于 
1.『要吐槽/耍嘴皮子 总是有得有』简单得很。
1.  要动手做总是 麻烦和费力。

不删除你这个Issue，是因为 无视你的吐槽，剩下的内容还是有些技术味

可惜就是点味了，你要能提交出你说的事，我就真心给你点赞了！

如果你要回Issue ，想好 :)

**Comment by SoXeon** [comment]
但@humt0ng 所指出问题我一一回复：
1. 编码规范的确一开始有问题，但是大家一起努力下，BeeHive还是有所进步的（功能&规范）；
2. 注释缺失：我个人认为是你英文水平有限，OC编写方法的可读性已经很高了，如有什么高见，请具体描述出来；
3. 接口设计混乱：若简单使用，统一使用BeeHive头文件中提供方法即可
4. UT的确是我的锅，入职到现在一直忙业务，这些基础的事情总是没有完善起来，最近也被老大拉去做后端，还要去忙双11=_=
5. BHContext是内部初始版本设计遗留下来的产物，作用的确不大，我们内部开发时也不怎么用到；

但是你说”这就是一个KPI项目“，我觉得言过了；
1. BeeHive是一个在DAU千万级项目App中实际运用过的，它在开发中解决了一些生产力的问题，改善了效率；
2. 解放生产力的同时，完成了对应效率提升、架构设计KPI，这有何不可？
3. 作为内部同学的确没有办法，把精力全部投入BeeHive中，但是每当有Pull request，我这边还是尽早去review，现在加入route&Service功能强化，都是社区同学的贡献；
4. 如果你愿意，please show your code？

**Comment by humt0ng** [comment]
我为之前的评价道歉。我会仔细阅尽所能帮助项目改进。

**Comment by oldratlee** [comment]
期望你的 提交、改进、贡献和付出  :)

**Comment by rexqin** [comment]
开源精神是在分享与回馈，如果觉得更新太慢，也可以fork把改进后的结果提交pull request。UT是不是要耦合进来 本身也是一个问题～
